name: exploring workflow

on: 
  workflow_dispatch:
  push:

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
    TEST_TAG: user/app:test
    LATEST_TAG: user/app:latest
jobs:
    unit-testing:
     name: unit testing
     services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017
     

     env:
        MONGO_URI: mongodb://localhost:27017/superData
        MONGO_USERNAME: non-prod-user
        MONGO_PASSWORD: non-prod-password
     strategy:
        matrix:
            os: [ubuntu-latest]
            node-version: [18]
            # exclude:
            #     - os: ubuntu-latest
            #       node-version: 18
     runs-on: ${{matrix.os}}
     steps:
        
      - name: Checkout your branch
        uses: actions/checkout@v4

      - name: Then install Node.js version - ${{matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}

      - name: install dependencies
        run: npm install

      - name: unit test
        id: unit-test
        run: npm test

      - name: archieve the results
        uses: actions/upload-artifact@v7
        if: success()
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: mocha-artifacts
 
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: test-results.xml


    coverage-code:
     container:
      image: node:18
  
     services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        options: 
         --name mongo
     
     env:
        MONGO_URI: mongodb://mongo:27017/superData
        MONGO_USERNAME: non-prod-user
        MONGO_PASSWORD: non-prod-password
    #  continue-on-error: true
     name: code-coverage
     runs-on: ubuntu-latest
     steps:
        
      - name: Checkout your branch
        uses: actions/checkout@v4

      # - name: Then install Node.js version - ${{matrix.node-version}}
      #   uses: actions/setup-node@v6
      #   with:
      #     node-version: ${{matrix.node-version}}

      - name: Cache NPM Dependencies
        uses: actions/cache@v6
        with:
          path: node_modules
          # using hashFiles to generate a unique hash based on the contents of package-lock.json
          # This ensures that the cache is updated whenever package-lock.json changes
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          

      - name: install dependencies
        run: npm install

      - name: coverage
        continue-on-error: true
        run: npm run coverage

      - name: archieve the results
        uses: actions/upload-artifact@v7
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: Code-Coverage-Result
 
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: coverage
          retention-days: 5
      


    docker:
     needs: [unit-testing, coverage-code]
     name: containerization
     runs-on: ubuntu-latest
     permissions:
        packages: write
     steps:
      - name: Checkout your branch
        uses: actions/checkout@v4
 
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.github_token }}

      # Set up QEMU and Docker Buildx to enable building multi-platform Docker images
      # QEMU allows you to emulate different CPU architectures, while Docker Buildx is a CLI plugin that extends the capabilities of Docker Build, enabling you to build images for multiple platforms.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      # this builds the Docker image for the specified platforms (linux/amd64 and linux/arm64) and pushes it to Docker Hub with the specified tags. The 'load: true' option allows the built image to be loaded into the local Docker daemon, making it available for testing in the next step.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and export to Docker
        uses: docker/build-push-action@v7
        with:
          load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{github.sha}}

      - name: Test
        run: |
          docker images
          docker run --name solar-system-app -d \
          -p 3000:3000 \
          -e "MONGO_URI=${MONGO_URI}" \
          -e "MONGO_USERNAME=${MONGO_USERNAME}" \
          -e "MONGO_PASSWORD=${MONGO_PASSWORD}" \
          ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{github.sha}}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{github.sha}}
            ghcr.io/${{ github.repository_owner }}/solar-system:${{github.sha}}
