name: resuse-workflow

on:
  workflow_call:
    inputs:
      MONGO_URI:
        required: true
        type: string

      k8s_version:
        required: false
        type: string
        default: latest

      environment:
        required: true
        type: string
        default: 'development'

      k8s_manifest_path:
        required: true
        type: string
        default: 'kubernetes/development/*.yaml'

    secrets:
      MONGO_PASSWORD:
        required: true
      kubeconfig:
        required: true

jobs:
  reuse-workflow:
    name: dev-deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.environment}}
      url: http://${{ steps.ingress-ip.outputs.APP_INGRESS_HOST }}

    outputs:
          app-ingress-host: ${{ steps.ingress-ip.outputs.APP_INGRESS_HOST }}

    steps:
      - name: Checkout your branch
        uses: actions/checkout@v4

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ inputs.k8s_version }}

      - name: set kubernetes context
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: fetch kubernetes cluster details
        run: |
          kubectl version
          echo ------------
          kubectl get nodes

      - name: Get Kubernetes node external IP
        id: get-ingress-ip
        run: |
          INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller \
          -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "INGRESS_IP=${INGRESS_IP}" >> $GITHUB_ENV

      - name: Replace tokens in manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{inputs.k8s_manifest_path}}/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Create development namespace
        run: |
          kubectl create namespace ${{ vars.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: create mongo-db-creds secret in kubernetes cluster
        run: |
          kubectl create secret generic mongo-db-creds \
            --from-literal=MONGO_URI="${{ inputs.MONGO_URI }}" \
            --from-literal=MONGO_USERNAME="${{ env.MONGO_USERNAME }}" \
            --from-literal=MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
            --namespace ${{ vars.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes cluster
        run: |
          kubectl apply -f kubernetes/development/deployment.yaml
          kubectl apply -f kubernetes/development/service.yaml
          kubectl apply -f kubernetes/development/ingress.yaml

      

      - name: set app ingress ip url output to other jobs
        id: ingress-ip
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.rules[0].host}')" >> "$GITHUB_OUTPUT"
          
    
